#!/usr/bin/bash

CMAKE_ARGS=()

CMAKE_ARGS+=("BUILD_SHARED_LIBS=OFF")
CMAKE_ARGS+=("CAFFE2_USE_MSVC_STATIC_RUNTIME=ON")

CMAKE_ARGS+=("CMAKE_BUILD_TYPE=debug")
CMAKE_ARGS+=("CMAKE_GENERATOR=Ninja")

CMAKE_ARGS+=("USE_NUMPY=ON")
CMAKE_ARGS+=("USE_ROCM=OFF")
CMAKE_ARGS+=("USE_CUDA=OFF")
CMAKE_ARGS+=("USE_CUDNN=OFF")
CMAKE_ARGS+=("USE_ITT=OFF")
CMAKE_ARGS+=("USE_GFLAGS=OFF")
CMAKE_ARGS+=("USE_OPENCV=OFF")
CMAKE_ARGS+=("USE_LMDB=OFF")
CMAKE_ARGS+=("USE_LEVELDB=OFF")
CMAKE_ARGS+=("USE_MPI=OFF")
CMAKE_ARGS+=("USE_OPENMP=OFF")
CMAKE_ARGS+=("USE_FBGEMM=OFF")
CMAKE_ARGS+=("USE_ASAN=OFF")

CMAKE_ARGS+=("BUILD_CAFFE2=OFF")
CMAKE_ARGS+=("BUILD_CAFFE2_OPS=OFF")
CMAKE_ARGS+=("BUILD_CAFFE2_MOBILE=OFF")
CMAKE_ARGS+=("BUILD_TEST=OFF")
CMAKE_ARGS+=("BUILD_JNI=OFF")
CMAKE_ARGS+=("BUILD_PYTHON=OFF")

for arg in ${CMAKE_ARGS[@]}; do
	export $arg
done

/usr/bin/env python pytorch/tools/build_libtorch.py
