#!/usr/bin/bash

GENERATOR="Ninja"
PYTORCH_DIR="pytorch"
PYTHON_VER=3.10

ARGS=()
ARGS+=("-Wno-dev")

ARGS+=("-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python${PYTHON_VER}")
ARGS+=("-DPYTHON_INCLUDE_DIR:PATH=/usr/include/python${PYTHON_VER}")
ARGS+=("-DPYTHON_LIBRARY:FILEPATH=/usr/lib/libpython${PYTHON_VER}.so")

ARGS+=("-G$GENERATOR")
ARGS+=("-DCMAKE_BUILD_TYPE=MinSizeRel")

ARGS+=("-DBUILD_SHARED_LIBS=OFF")
ARGS+=("-DBUILD_CAFFE2=OFF")
ARGS+=("-DBUILD_PYTHON=OFF")
ARGS+=("-DBUILD_TEST=OFF")
ARGS+=("-DBUILD_LAZY_TS_BACKEND=OFF")

ARGS+=("-DUSE_FBGEMM=ON")
ARGS+=("-DUSE_NNPACK=ON")
ARGS+=("-DBUILD_CUSTOM_PROTOBUF=ON")

ARGS+=("-DUSE_NCCL=OFF")
ARGS+=("-DUSE_CUDA=OFF")
ARGS+=("-DUSE_MKLDNN=OFF")
ARGS+=("-DUSE_GLOO=OFF")
ARGS+=("-DUSE_KINETO=OFF")
ARGS+=("-DUSE_NUMPY=OFF")
ARGS+=("-DUSE_OPENMP=OFF")
ARGS+=("-DUSE_XNNPACK=OFF")
ARGS+=("-DUSE_DISTRIBUTED=OFF")
ARGS+=("-DUSE_MPI=OFF")
ARGS+=("-DUSE_TENSORPIPE=OFF")
ARGS+=("-DUSE_PYTORCH_QNNPACK=OFF")
ARGS+=("-DUSE_QNNPACK=OFF")
ARGS+=("-DUSE_FFTW=OFF")
ARGS+=("-DCMAKE_INSTALL_PREFIX:PATH=${PWD}/${PYTORCH_DIR}/build/install")

patch ${PYTORCH_DIR}/CMakeLists.txt -i general-flags.patch
patch ${PYTORCH_DIR}/third_party/fbgemm/CMakeLists.txt -i fbgemm-flags.patch

cd $PYTORCH_DIR
cmake . -B build ${ARGS[@]}
cd build
cmake --build . --target install
