GENERATOR="Ninja"
PYTORCH_DIR="pytorch"

ARGS=()
ARGS+=("-G$GENERATOR")
ARGS+=("-DCMAKE_BUILD_TYPE=MinSizeRel")
ARGS+=("-DBUILD_SHARED_LIBS=OFF")
ARGS+=("-DBUILD_CAFFE2_MOBILE=OFF")
ARGS+=("-DCAFFE2_USE_MSVC_STATIC_RUNTIME=ON")
ARGS+=("-DMSVC_Z7_OVERRIDE=ON")
ARGS+=("-DUSE_CUDA=OFF")
ARGS+=("-DBUILD_PYTHON=OFF")
ARGS+=("-DBUILD_TEST=OFF")
ARGS+=("-DUSE_MKLDNN=OFF")

cd $PYTORCH_DIR
cmake . -B build ${ARGS[@]}
cd build
${GENERATOR,,}
