set BUILD_SHARED_LIBS=OFF
set CAFFE2_USE_MSVC_STATIC_RUNTIME=ON

# set CMAKE_BUILD_TYPE=DEBUG

set USE_GOLD_LINKER=OFF

set BUILD_CAFFE2=OFF
set BUILD_CAFFE2_OPS=OFF
set BUILD_CAFFE2_MOBILE=OFF

set BUILD_BINARY=OFF
set BUILD_CUSTOM_PROTOBUF=OFF

set BUILD_DOCS=OFF
set BUILD_PYTHON=OFF
set BUILD_TEST=OFF
set BUILD_JNI=OFF
set BUILD_MOBILE_AUTOGRAD=OFF
set BUILD_LITE_INTERPRETER=OFF
set INTERN_BUILD_MOBILE=OFF
set USE_BLAS=1
set USE_LAPACK=0

set USE_ASAN=OFF
set USE_CPP_CODE_COVERAGE=OFF
set USE_CUDA=OFF
set USE_ROCM=OFF

set USE_EIGEN_FOR_BLAS=ON
set USE_FBGEMM=OFF
set USE_FBGEMM=OFF
set USE_KINETO=OFF
set USE_FFMPEG=OFF
set USE_GFLAGS=OFF
set USE_GLOG=OFF
set USE_LEVELDB=OFF
set USE_LITE_PROTO=OFF
set USE_LMDB=OFF
set USE_METAL=OFF
set USE_PYTORCH_METAL=OFF
set USE_PYTORCH_METAL_set=OFF
set USE_MPS=OFF
set USE_FFTW=ON
set USE_MKLDNN=ON
set USE_MKLDNN_ACL=OFF
set USE_MKLDNN_CBLAS=OFF
set USE_UCC=OFF
set USE_ITT=OFF
set USE_NCCL=OFF
set USE_NNPACK=ON
set USE_NUMPY=ON
set USE_OBSERVERS=OFF
set USE_OPENCL=OFF
set USE_OPENCV=OFF
set USE_OPENMP=OFF
set USE_TBB=OFF
set USE_VULKAN=OFF
set USE_PROF=OFF
set USE_QNNPACK=OFF
set USE_PYTORCH_QNNPACK=OFF
set USE_XNNPACK=ON
set USE_REDIS=OFF
set USE_ROCKSDB=OFF
set USE_ZMQ=OFF
set USE_DISTRIBUTED=OFF
set USE_DEPLOY=OFF
set USE_COREML_DELEGATE=OFF
set BUILD_LAZY_TS_BACKEND=OFF

py pytorch\tools\build_libtorch.py
