@echo off

set GENERATOR=Ninja
set PYTORCH_DIR=pytorch

cd %PYTORCH_DIR%

cmake . -B build -G%GENERATOR% -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_SHARED_LIBS=OFF -DBUILD_CAFFE2_MOBILE=OFF -DCAFFE2_USE_MSVC_STATIC_RUNTIME=ON -DMSVC_Z7_OVERRIDE=ON -DUSE_CUDA=OFF -DBUILD_PYTHON=OFF -DBUILD_TEST=OFF -DUSE_MKLDDN=OFF -DBUILD_CAFFE2=OFF -DUSE_GLOO=OFF -DUSE_KINETO=OFF -DUSE_FFTW=OFF -DUSE_NUMPY=OFF -DUSE_NNPACK=OFF -DUSE_OPENMP=OFF -DUSE_XNNPACK=OFF -DUSE_DISTRIBUTED=OFF -DUSE_MPI=OFF -DUSE_TENSORPIPE=OFF -DBUILD_LAZY_TS_BACKEND=OFF -DUSE_PYTORCH_QNNPACK=OFF -DUSE_FBGEMM=OFF -DUSE_QNNPACK=OFF -DUSE_EIGEN_FOR_BLAS=OFF

cd build
ninja
