@echo off

set GENERATOR=Ninja
set PYTORCH_DIR=pytorch

cd %PYTORCH_DIR%

cmake . -B build -G%GENERATOR% -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_SHARED_LIBS=OFF -DBUILD_CAFFE2_MOBILE=OFF -DCAFFE2_USE_MSVC_STATIC_RUNTIME=ON -DMSVC_Z7_OVERRIDE=ON -DUSE_CUDA=OFF -DBUILD_PYTHON=OFF -DBUILD_TEST=OFF -DUSE_MKLDDN=OFF -DUSE_TENSORPIPE=OFF

cd build
ninja
